apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
  namespace: amazon-cloudwatch
data:
  cloudwatch-agent-config.json: |
    {
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/var/log/eb-engine.log",
                "log_group_name": "/eks/lkrm-staging/var/log/eb-engine.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/eb-hooks.log",
                "log_group_name": "/eks/lkrm-staging/var/log/eb-hooks.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/nginx/access.log",
                "log_group_name": "/eks/lkrm-staging/var/log/nginx/access.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/nginx/error.log",
                "log_group_name": "/eks/lkrm-staging/var/log/nginx/error.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/httpd/access.log",
                "log_group_name": "/eks/lkrm-staging/var/log/httpd/access.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/httpd/error.log",
                "log_group_name": "/eks/lkrm-staging/var/log/httpd/error.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/web.stdout.log",
                "log_group_name": "/eks/lkrm-staging/var/log/web.stdout.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/celery_worker.stdout.log",
                "log_group_name": "/eks/lkrm-staging/var/log/celery_worker.stdout.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/var/log/celery_beat.stdout.log",
                "log_group_name": "/eks/lkrm-staging/var/log/celery_beat.stdout.log",
                "log_stream_name": "{instance_id}"
              }
            ]    
          }
        }
      }
    }
    