apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudwatch-agent
  namespace: amazon-cloudwatch
spec:
  selector:
    matchLabels:
      name: cloudwatch-agent # Label to match the pods managed by this DaemonSet
  template:
    metadata:
      labels:
        name: cloudwatch-agent # Label applied to the pods created by this DaemonSet
    spec:
      serviceAccountName: cloudwatch-agent-service-account # The service account
      containers:
        - name: cloudwatch-agent
          image: amazon/cloudwatch-agent:1.300048.1b904 # Docker image for the CloudWatch agent
          resources:
            limits:
              cpu: 200m # Maximum CPU request for the container
              memory: 200Mi # Maximum memory limit for the container
            requests:
              cpu: 100m # Minimum CPU request for the container
              memory: 100Mi # Minimum memory request for the container
          volumeMounts:
            - name: config
              mountPath: /etc/cwagentconfig # Mount the config volume to this path
            - name: varlog
              mountPath: /var/log # Mount the varlog volume to this path
      volumes:
        - name: config
          configMap:
            name: cloudwatch-agent-config # ConfigMap containing the CloudWatch agent configuration
        - name: varlog
          hostPath:
            path: /var/log # Host path to be mounted into the container
