apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudwatch-agent-config
data:
  cloudwatch-agent-config.json: |
    {
      "metrics": {
        "namespace": "EKS/lkrm-prod-metrics",
        "append_dimensions": {
          "AppName": "lkrm-prod",
          "InstanceId": "${aws:InstanceId}"
        },
        "metrics_collected": {
            "mem": {
              "measurement": ["mem_used_percent"],
              "metrics_collection_interval": 60
            },
            "cpu": {
              "measurement": [
                "cpu_usage_idle",
                "cpu_usage_iowait",
                "cpu_usage_user",
                "cpu_usage_system"
              ],
              "metrics_collection_interval": 60
            }
          }
          },
      "logs": {
        "logs_collected": {
          "files": {
            "collect_list": [
              {
                "file_path": "/mnt/logs/nginx/access.log*",
                "log_group_name": "/eks/lkrm-prod/mnt/logs/nginx/access.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/mnt/logs/nginx/error.log*",
                "log_group_name": "/eks/lkrm-prod/mnt/logs/nginx/error.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/mnt/logs/httpd/access.log*",
                "log_group_name": "/eks/lkrm-prod/mnt/logs/httpd/access.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/mnt/logs/httpd/error.log*",
                "log_group_name": "/eks/lkrm-prod/mnt/logs/httpd/error.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/mnt/logs/web.stdout.log*",
                "log_group_name": "/eks/lkrm-prod/mnt/logs/web.stdout.log",
                "log_stream_name": "{instance_id}"
              },
              {
                "file_path": "/mnt/logs/realtime_monitor.log*",
                "log_group_name": "/eks/lkrm-staging/mnt/logs/realtime_monitor.log",
                "log_stream_name": "{instance_id}"
              }
            ]    
          }
        }
      }
    }
    