apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudwatch-agent-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::{ { AWS_ACCOUNT_ID } }:role/{ { AWS_CLOUDWATCH_ROLE_NAME } }
